[workspace]
resolver = "3"
members = [
    "001-counter",
    "002-mul_div",
    "003-camelot-swapping",
    "005-counter-bobcat-return",
    "006-supercats"
]

[workspace.dependencies]
bobcat-sdk.path = "../bobcat-sdk"

[patch.crates-io]
bobcat-cd.path = "../bobcat-cd"
bobcat-entry.path = "../bobcat-entry"
bobcat-maths.path = "../bobcat-maths"

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "s"
